const a = /* @__PURE__ */ location.pathname.split("/").slice(0, -1).join("/"), l = [
  a + "/_app/immutable/chunks/config.route.faae0b7b.js",
  a + "/_app/immutable/chunks/dynamic.route.9faa91fa.js",
  a + "/_app/immutable/chunks/generic.route.e379ba96.js",
  a + "/_app/immutable/chunks/icon.route.becfec0b.js",
  a + "/_app/immutable/chunks/playground.route.80883043.js",
  a + "/_app/immutable/chunks/focustrack.route.ec6093a1.js",
  a + "/_app/immutable/chunks/default.route.26c149f6.js",
  a + "/_app/immutable/chunks/playground.route.cb673a11.js",
  a + "/_app/immutable/chunks/stack.route.17fbea9f.js",
  a + "/_app/immutable/chunks/custom.route.42a9808f.js",
  a + "/_app/immutable/chunks/default.route.0c8a0d1c.js",
  a + "/_app/immutable/chunks/playground.route.ca02be87.js",
  a + "/_app/immutable/chunks/config.route.376b6516.js",
  a + "/_app/immutable/chunks/customTemplate.route.7f6b9e55.js",
  a + "/_app/immutable/chunks/default.route.b7db8e5e.js",
  a + "/_app/immutable/chunks/form.route.c971f529.js",
  a + "/_app/immutable/chunks/playground.route.4bc39cf3.js",
  a + "/_app/immutable/chunks/readonly.route.654130e7.js",
  a + "/_app/immutable/chunks/select.route.a9432ff1.js",
  a + "/_app/immutable/chunks/transition.route.5fd65779.js",
  a + "/_app/immutable/entry/start.9795cccc.js",
  a + "/_app/immutable/chunks/Config.route.7a471a30.js",
  a + "/_app/immutable/chunks/Dynamic.route.bb88327f.js",
  a + "/_app/immutable/chunks/Generic.route.04795f7a.js",
  a + "/_app/immutable/chunks/Icon.route.dad41adb.js",
  a + "/_app/immutable/chunks/Playground.route.13869e0f.js",
  a + "/_app/immutable/chunks/Focustrack.route.6a73deb1.js",
  a + "/_app/immutable/chunks/Default.route.ed075beb.js",
  a + "/_app/immutable/chunks/Playground.route.a1543103.js",
  a + "/_app/immutable/chunks/Stack.route.9cbca26b.js",
  a + "/_app/immutable/chunks/Custom.route.6ec1a928.js",
  a + "/_app/immutable/chunks/Default.route.805ae506.js",
  a + "/_app/immutable/chunks/Playground.route.3677c70b.js",
  a + "/_app/immutable/chunks/Config.route.3bf90227.js",
  a + "/_app/immutable/chunks/CustomTemplate.route.90ef5bba.js",
  a + "/_app/immutable/chunks/Default.route.67acd204.js",
  a + "/_app/immutable/chunks/Form.route.264b2bef.js",
  a + "/_app/immutable/chunks/Playground.route.5df093c9.js",
  a + "/_app/immutable/chunks/Readonly.route.abce1d54.js",
  a + "/_app/immutable/chunks/Select.route.7f50c64d.js",
  a + "/_app/immutable/chunks/Transition.route.9db08c1f.js",
  a + "/_app/immutable/chunks/Config.route.b147084d.js",
  a + "/_app/immutable/chunks/Dynamic.route.e4142488.js",
  a + "/_app/immutable/chunks/Generic.route.8bab0d48.js",
  a + "/_app/immutable/chunks/Icon.route.07dd69d1.js",
  a + "/_app/immutable/chunks/Playground.route.2cdc4cab.js",
  a + "/_app/immutable/chunks/Focustrack.route.fe90b97f.js",
  a + "/_app/immutable/chunks/Default.route.1021abc6.js",
  a + "/_app/immutable/chunks/Playground.route.408a8117.js",
  a + "/_app/immutable/chunks/Stack.route.a0e891ef.js",
  a + "/_app/immutable/chunks/Custom.route.9acedddf.js",
  a + "/_app/immutable/chunks/Default.route.a3a550bd.js",
  a + "/_app/immutable/chunks/Playground.route.f6c2d11b.js",
  a + "/_app/immutable/chunks/Config.route.d6f7594e.js",
  a + "/_app/immutable/chunks/CustomTemplate.route.2cfe5136.js",
  a + "/_app/immutable/chunks/Default.route.dbc6041b.js",
  a + "/_app/immutable/chunks/Form.route.3beb4f72.js",
  a + "/_app/immutable/chunks/Playground.route.a1a7efc0.js",
  a + "/_app/immutable/chunks/Readonly.route.ca6e4653.js",
  a + "/_app/immutable/chunks/Select.route.7f878794.js",
  a + "/_app/immutable/chunks/Transition.route.bfc0eba9.js",
  a + "/_app/immutable/entry/app.0b05b120.js",
  a + "/_app/immutable/assets/0.f721b913.css",
  a + "/_app/immutable/nodes/0.92fed227.js",
  a + "/_app/immutable/assets/bootstrap.e729f290.css",
  a + "/_app/immutable/nodes/1.6b8a24cb.js",
  a + "/_app/immutable/nodes/10.342fad7e.js",
  a + "/_app/immutable/nodes/11.316acf0a.js",
  a + "/_app/immutable/nodes/12.fc8f1b2a.js",
  a + "/_app/immutable/nodes/13.5b3a876d.js",
  a + "/_app/immutable/nodes/14.9d4545c1.js",
  a + "/_app/immutable/nodes/15.00da4236.js",
  a + "/_app/immutable/nodes/16.b7dd1cee.js",
  a + "/_app/immutable/nodes/17.ae7b233f.js",
  a + "/_app/immutable/nodes/18.c26de854.js",
  a + "/_app/immutable/nodes/19.3d493fb9.js",
  a + "/_app/immutable/assets/2.e5320fe0.css",
  a + "/_app/immutable/nodes/2.7b1d8dda.js",
  a + "/_app/immutable/nodes/20.b90cc2f3.js",
  a + "/_app/immutable/nodes/21.bda34c87.js",
  a + "/_app/immutable/nodes/22.fc45ef69.js",
  a + "/_app/immutable/nodes/23.bc569fa9.js",
  a + "/_app/immutable/nodes/24.c88de8da.js",
  a + "/_app/immutable/nodes/25.bee5768e.js",
  a + "/_app/immutable/nodes/3.a25f10bf.js",
  a + "/_app/immutable/nodes/4.07a55bdc.js",
  a + "/_app/immutable/nodes/5.2b526f6d.js",
  a + "/_app/immutable/nodes/6.f8fe959c.js",
  a + "/_app/immutable/assets/7.6a4947a3.css",
  a + "/_app/immutable/nodes/7.e5412197.js",
  a + "/_app/immutable/nodes/8.ca56f19f.js",
  a + "/_app/immutable/nodes/9.f0c0f01c.js",
  a + "/_app/immutable/assets/ApiDoc.88a4ab5e.css",
  a + "/_app/immutable/assets/Playground.93a180bb.css",
  a + "/_app/immutable/assets/Sample.f0981b31.css",
  a + "/_app/immutable/chunks/ApiDoc.91e5f5be.js",
  a + "/_app/immutable/chunks/ComponentPage.2ffa1b28.js",
  a + "/_app/immutable/chunks/Playground.7197c73f.js",
  a + "/_app/immutable/chunks/Sample.7dcb6ad7.js",
  a + "/_app/immutable/chunks/Svg.62cf5398.js",
  a + "/_app/immutable/chunks/api.82f78273.js",
  a + "/_app/immutable/chunks/api.cb0be0db.js",
  a + "/_app/immutable/chunks/api.e8d45d7f.js",
  a + "/_app/immutable/chunks/api.fec5e31a.js",
  a + "/_app/immutable/chunks/app.8c876633.js",
  a + "/_app/immutable/chunks/each.c1957c61.js",
  a + "/_app/immutable/chunks/index.62d994b0.js",
  a + "/_app/immutable/chunks/modal.4adda62b.js",
  a + "/_app/immutable/chunks/navigation.cc43d7fd.js",
  a + "/_app/immutable/chunks/preload-helper.a4192956.js",
  a + "/_app/immutable/chunks/scheduler.bebea13f.js",
  a + "/_app/immutable/chunks/singletons.cbb8f123.js",
  a + "/_app/immutable/chunks/stores.40a59639.js",
  a + "/_app/immutable/chunks/stores.539c6659.js",
  a + "/angular/samples/3rdpartylicenses.txt",
  a + "/angular/samples/assets/logo.svg",
  a + "/angular/samples/favicon.ico",
  a + "/angular/samples/index.html",
  a + "/angular/samples/main.a69a7f54c9b9c251.js",
  a + "/angular/samples/polyfills.7eb15e615c408027.js",
  a + "/angular/samples/runtime.c73397b5506956dd.js",
  a + "/angular/samples/styles.4e967a3244a1c72b.css",
  a + "/react/samples/assets/favicon-17e50649.svg",
  a + "/react/samples/assets/index-44fc3ec8.css",
  a + "/react/samples/assets/index-4c048243.js",
  a + "/react/samples/index.html",
  a + "/_app/immutable/assets/Code.a21cc7ad.css",
  a + "/_app/immutable/chunks/Code.4a9437c7.js",
  a + "/svelte/samples/assets/favicon-17e50649.svg",
  a + "/svelte/samples/assets/index-975ae34b.css",
  a + "/svelte/samples/assets/index-e6c85152.js",
  a + "/svelte/samples/index.html"
], i = [
  a + "/favicon.svg"
], r = [
  a + "/",
  a + "/angular/components/alert/examples",
  a + "/react/components/alert/examples",
  a + "/svelte/components/alert/examples",
  a + "/angular/components/alert",
  a + "/angular/components/modal",
  a + "/angular/components/pagination",
  a + "/angular/components/rating",
  a + "/angular/utilities/focustrack",
  a + "/angular/utilities/transition",
  a + "/angular/components/alert/api",
  a + "/angular/components/alert/playground",
  a + "/react/components/alert",
  a + "/react/components/modal",
  a + "/react/components/pagination",
  a + "/react/components/rating",
  a + "/react/utilities/focustrack",
  a + "/react/utilities/transition",
  a + "/react/components/alert/api",
  a + "/react/components/alert/playground",
  a + "/svelte/components/alert",
  a + "/svelte/components/modal",
  a + "/svelte/components/pagination",
  a + "/svelte/components/rating",
  a + "/svelte/utilities/focustrack",
  a + "/svelte/utilities/transition",
  a + "/svelte/components/alert/api",
  a + "/svelte/components/alert/playground",
  a + "/angular/components/modal/examples",
  a + "/angular/components/modal/api",
  a + "/angular/components/modal/playground",
  a + "/angular/components/pagination/examples",
  a + "/angular/components/pagination/api",
  a + "/angular/components/pagination/playground",
  a + "/angular/components/rating/examples",
  a + "/angular/components/rating/api",
  a + "/angular/components/rating/playground",
  a + "/react/components/modal/examples",
  a + "/react/components/modal/api",
  a + "/react/components/modal/playground",
  a + "/react/components/pagination/examples",
  a + "/react/components/pagination/api",
  a + "/react/components/pagination/playground",
  a + "/react/components/rating/examples",
  a + "/react/components/rating/api",
  a + "/react/components/rating/playground",
  a + "/svelte/components/modal/examples",
  a + "/svelte/components/modal/api",
  a + "/svelte/components/modal/playground",
  a + "/svelte/components/pagination/examples",
  a + "/svelte/components/pagination/api",
  a + "/svelte/components/pagination/playground",
  a + "/svelte/components/rating/examples",
  a + "/svelte/components/rating/api",
  a + "/svelte/components/rating/playground"
], b = "1691067817118", c = `cache-${b}`, o = [...l.map((s) => s.replace(/\/index\.html$/, "/")), ...r, ...i], d = (s) => {
  const e = [], t = [], p = /[.-]\w{8,}\.\w{2,4}$/;
  for (const n of s)
    (p.test(n) ? e : t).push(n);
  return { withHash: e, withoutHash: t };
};
self.addEventListener("install", (s) => {
  s.waitUntil(
    (async () => {
      const e = await caches.open(c), { withHash: t, withoutHash: p } = d(o), n = [];
      await Promise.all(
        t.map(async (u) => {
          const m = await caches.match(u);
          m != null && m.ok ? e.put(u, m) : n.push(u);
        })
      ), await e.addAll([...n, ...p]), await self.skipWaiting();
    })()
  );
});
self.addEventListener("activate", (s) => {
  s.waitUntil(
    (async () => {
      await self.clients.claim(), await Promise.all((await caches.keys()).filter((e) => e !== c).map((e) => caches.delete(e)));
    })()
  );
});
self.addEventListener("fetch", (s) => {
  const e = new URL(s.request.url);
  s.request.method === "GET" && o.includes(e.pathname) && s.respondWith(
    (async () => await (await caches.open(c)).match(e.pathname))()
  );
});
