const a = /* @__PURE__ */ location.pathname.split("/").slice(0, -1).join("/"), l = [
  a + "/_app/immutable/chunks/default.route.c57e0ad2.js",
  a + "/_app/immutable/chunks/playground.route.5cb7b9ef.js",
  a + "/_app/immutable/chunks/dynamic.route.c274edb9.js",
  a + "/_app/immutable/chunks/generic.route.e379ba96.js",
  a + "/_app/immutable/chunks/icon.route.da21c95e.js",
  a + "/_app/immutable/chunks/playground.route.80883043.js",
  a + "/_app/immutable/chunks/default.route.26c149f6.js",
  a + "/_app/immutable/chunks/playground.route.cb673a11.js",
  a + "/_app/immutable/chunks/stack.route.17fbea9f.js",
  a + "/_app/immutable/chunks/custom.route.65a2456a.js",
  a + "/_app/immutable/chunks/default.route.9ba740f2.js",
  a + "/_app/immutable/chunks/playground.route.ca02be87.js",
  a + "/_app/immutable/chunks/customTemplate.route.7f6b9e55.js",
  a + "/_app/immutable/chunks/default.route.b7db8e5e.js",
  a + "/_app/immutable/chunks/form.route.c971f529.js",
  a + "/_app/immutable/chunks/playground.route.4bc39cf3.js",
  a + "/_app/immutable/chunks/readonly.route.a057a9fb.js",
  a + "/_app/immutable/chunks/demo.bfd80df8.js",
  a + "/_app/immutable/entry/start.d835f476.js",
  a + "/_app/immutable/chunks/Default.route.d34af912.js",
  a + "/_app/immutable/chunks/Playground.route.8dd436c1.js",
  a + "/_app/immutable/chunks/Dynamic.route.bb88327f.js",
  a + "/_app/immutable/chunks/Generic.route.04795f7a.js",
  a + "/_app/immutable/chunks/Icon.route.29d39d4f.js",
  a + "/_app/immutable/chunks/Playground.route.13869e0f.js",
  a + "/_app/immutable/chunks/Default.route.ed075beb.js",
  a + "/_app/immutable/chunks/Playground.route.a1543103.js",
  a + "/_app/immutable/chunks/Stack.route.9cbca26b.js",
  a + "/_app/immutable/chunks/Custom.route.d9802bfa.js",
  a + "/_app/immutable/chunks/Default.route.00edef85.js",
  a + "/_app/immutable/chunks/Playground.route.3677c70b.js",
  a + "/_app/immutable/chunks/CustomTemplate.route.90ef5bba.js",
  a + "/_app/immutable/chunks/Default.route.67acd204.js",
  a + "/_app/immutable/chunks/Form.route.264b2bef.js",
  a + "/_app/immutable/chunks/Playground.route.5df093c9.js",
  a + "/_app/immutable/chunks/Readonly.route.4833956c.js",
  a + "/_app/immutable/chunks/Default.route.a86638ee.js",
  a + "/_app/immutable/chunks/Playground.route.775a1773.js",
  a + "/_app/immutable/chunks/Dynamic.route.a9d9e874.js",
  a + "/_app/immutable/chunks/Generic.route.8bab0d48.js",
  a + "/_app/immutable/chunks/Icon.route.07dd69d1.js",
  a + "/_app/immutable/chunks/Icon.2156b2f4.js",
  a + "/_app/immutable/chunks/Playground.route.2cdc4cab.js",
  a + "/_app/immutable/chunks/Default.route.1021abc6.js",
  a + "/_app/immutable/chunks/Playground.route.408a8117.js",
  a + "/_app/immutable/chunks/Stack.route.a0e891ef.js",
  a + "/_app/immutable/chunks/StackModal.e85f6954.js",
  a + "/_app/immutable/chunks/Custom.route.629bc057.js",
  a + "/_app/immutable/chunks/CustomPages.efa871a7.js",
  a + "/_app/immutable/chunks/Default.route.d9ff694f.js",
  a + "/_app/immutable/chunks/Playground.route.f6c2d11b.js",
  a + "/_app/immutable/chunks/CustomTemplate.route.2cfe5136.js",
  a + "/_app/immutable/chunks/Default.route.dbc6041b.js",
  a + "/_app/immutable/chunks/Form.route.3beb4f72.js",
  a + "/_app/immutable/chunks/Playground.route.a1a7efc0.js",
  a + "/_app/immutable/chunks/Readonly.route.b88e3005.js",
  a + "/_app/immutable/entry/app.182b1269.js",
  a + "/_app/immutable/assets/0.e9bda849.css",
  a + "/_app/immutable/nodes/0.d858c21b.js",
  a + "/_app/immutable/assets/bootstrap.e729f290.css",
  a + "/_app/immutable/nodes/1.ce3614e0.js",
  a + "/_app/immutable/nodes/10.c393776c.js",
  a + "/_app/immutable/nodes/11.01c3f9d5.js",
  a + "/_app/immutable/nodes/12.18ad380e.js",
  a + "/_app/immutable/nodes/13.b75de55f.js",
  a + "/_app/immutable/nodes/14.661f9dfe.js",
  a + "/_app/immutable/nodes/15.25a70a3b.js",
  a + "/_app/immutable/nodes/16.9d76318a.js",
  a + "/_app/immutable/nodes/17.d33b8586.js",
  a + "/_app/immutable/nodes/18.842e4d03.js",
  a + "/_app/immutable/nodes/19.a7c5830c.js",
  a + "/_app/immutable/assets/2.e5320fe0.css",
  a + "/_app/immutable/nodes/2.e011a4f4.js",
  a + "/_app/immutable/nodes/20.7704fffd.js",
  a + "/_app/immutable/nodes/21.377788dd.js",
  a + "/_app/immutable/nodes/22.499c8f9e.js",
  a + "/_app/immutable/nodes/23.7f4cabab.js",
  a + "/_app/immutable/nodes/24.ff7ad0f3.js",
  a + "/_app/immutable/nodes/25.ee857855.js",
  a + "/_app/immutable/nodes/26.c3753e75.js",
  a + "/_app/immutable/nodes/27.d2eb7019.js",
  a + "/_app/immutable/nodes/28.db8dc8d1.js",
  a + "/_app/immutable/nodes/3.f038ca68.js",
  a + "/_app/immutable/nodes/4.4363f7a5.js",
  a + "/_app/immutable/nodes/5.8fd2449f.js",
  a + "/_app/immutable/nodes/6.5f955e66.js",
  a + "/_app/immutable/nodes/7.ab2bab67.js",
  a + "/_app/immutable/assets/8.6a4947a3.css",
  a + "/_app/immutable/nodes/8.44b1429e.js",
  a + "/_app/immutable/nodes/9.4ff56696.js",
  a + "/_app/immutable/assets/ApiDoc.88a4ab5e.css",
  a + "/_app/immutable/assets/LinkHeading.b3133932.css",
  a + "/_app/immutable/assets/Playground.93a180bb.css",
  a + "/_app/immutable/assets/Sample.fd01a369.css",
  a + "/_app/immutable/chunks/ApiDoc.d20ed8cf.js",
  a + "/_app/immutable/chunks/ComponentPage.e5570d67.js",
  a + "/_app/immutable/chunks/LinkHeading.4117e805.js",
  a + "/_app/immutable/chunks/Playground.bf2fe129.js",
  a + "/_app/immutable/chunks/Sample.b2add3c3.js",
  a + "/_app/immutable/chunks/Svg.4ea3afa0.js",
  a + "/_app/immutable/chunks/api.015b71f2.js",
  a + "/_app/immutable/chunks/api.64b992cd.js",
  a + "/_app/immutable/chunks/api.82f78273.js",
  a + "/_app/immutable/chunks/api.ce0ad4d6.js",
  a + "/_app/immutable/chunks/api.f9342382.js",
  a + "/_app/immutable/chunks/app.8c876633.js",
  a + "/_app/immutable/chunks/each.c25865bc.js",
  a + "/_app/immutable/chunks/index.6f5125a4.js",
  a + "/_app/immutable/chunks/index.es.5c333286.js",
  a + "/_app/immutable/chunks/modal.becd5ecb.js",
  a + "/_app/immutable/chunks/navigation.d26146de.js",
  a + "/_app/immutable/chunks/preload-helper.a4192956.js",
  a + "/_app/immutable/chunks/scheduler.2ed3e821.js",
  a + "/_app/immutable/chunks/singletons.86b8b642.js",
  a + "/_app/immutable/chunks/stores.10573310.js",
  a + "/_app/immutable/chunks/stores.ef211323.js",
  a + "/angular/samples/3rdpartylicenses.txt",
  a + "/angular/samples/assets/logo.svg",
  a + "/angular/samples/favicon.ico",
  a + "/angular/samples/index.html",
  a + "/angular/samples/main.c003493e679d222e.js",
  a + "/angular/samples/polyfills.2cca545e4d8bf0a3.js",
  a + "/angular/samples/runtime.c73397b5506956dd.js",
  a + "/angular/samples/styles.2a19969ca6fc433d.css",
  a + "/react/samples/assets/favicon-17e50649.svg",
  a + "/react/samples/assets/index-07b6f2af.js",
  a + "/react/samples/assets/index-83719a1c.css",
  a + "/react/samples/index.html",
  a + "/_app/immutable/assets/Code.25188a17.css",
  a + "/_app/immutable/chunks/Code.d3030d6d.js",
  a + "/_app/immutable/chunks/angular.a665b734.js",
  a + "/_app/immutable/chunks/index.ba4af4d9.js",
  a + "/_app/immutable/chunks/package.36faae00.js",
  a + "/_app/immutable/chunks/polyfills.ca93877f.js",
  a + "/_app/immutable/chunks/raw-loader.d.af52f768.js",
  a + "/_app/immutable/chunks/tsconfig.37d3f7d2.js",
  a + "/_app/immutable/chunks/index.38ed7db5.js",
  a + "/_app/immutable/chunks/index.9a9b4a9b.js",
  a + "/_app/immutable/chunks/package.3997bbdd.js",
  a + "/_app/immutable/chunks/vite-env.d.7838e369.js",
  a + "/_app/immutable/chunks/tsconfig.f7d9505e.js",
  a + "/_app/immutable/chunks/vite.config.9d6850ed.js",
  a + "/_app/immutable/chunks/index.9d3e169c.js",
  a + "/_app/immutable/chunks/package.391f07a9.js",
  a + "/_app/immutable/chunks/vite-env.d.2f957e98.js",
  a + "/_app/immutable/chunks/svelte.config.1307a686.js",
  a + "/_app/immutable/chunks/tsconfig.aa2595b6.js",
  a + "/_app/immutable/chunks/vite.config.17a73b3a.js",
  a + "/svelte/samples/assets/favicon-17e50649.svg",
  a + "/svelte/samples/assets/index-a5fd51a5.css",
  a + "/svelte/samples/assets/index-b368eb04.js",
  a + "/svelte/samples/index.html"
], i = [
  a + "/favicon.svg"
], b = [
  a + "/",
  a + "/angular/components/accordion/examples",
  a + "/react/components/accordion/examples",
  a + "/svelte/components/accordion/examples",
  a + "/angular/components/accordion",
  a + "/angular/components/alert",
  a + "/angular/components/modal",
  a + "/angular/components/pagination",
  a + "/angular/components/rating",
  a + "/angular/components/accordion/api",
  a + "/angular/components/accordion/playground",
  a + "/react/components/accordion",
  a + "/react/components/alert",
  a + "/react/components/modal",
  a + "/react/components/pagination",
  a + "/react/components/rating",
  a + "/react/components/accordion/api",
  a + "/react/components/accordion/playground",
  a + "/svelte/components/accordion",
  a + "/svelte/components/alert",
  a + "/svelte/components/modal",
  a + "/svelte/components/pagination",
  a + "/svelte/components/rating",
  a + "/svelte/components/accordion/api",
  a + "/svelte/components/accordion/playground",
  a + "/angular/components/alert/examples",
  a + "/angular/components/alert/api",
  a + "/angular/components/alert/playground",
  a + "/angular/components/modal/examples",
  a + "/angular/components/modal/api",
  a + "/angular/components/modal/playground",
  a + "/angular/components/pagination/examples",
  a + "/angular/components/pagination/api",
  a + "/angular/components/pagination/playground",
  a + "/angular/components/rating/examples",
  a + "/angular/components/rating/api",
  a + "/angular/components/rating/playground",
  a + "/react/components/alert/examples",
  a + "/react/components/alert/api",
  a + "/react/components/alert/playground",
  a + "/react/components/modal/examples",
  a + "/react/components/modal/api",
  a + "/react/components/modal/playground",
  a + "/react/components/pagination/examples",
  a + "/react/components/pagination/api",
  a + "/react/components/pagination/playground",
  a + "/react/components/rating/examples",
  a + "/react/components/rating/api",
  a + "/react/components/rating/playground",
  a + "/svelte/components/alert/examples",
  a + "/svelte/components/alert/api",
  a + "/svelte/components/alert/playground",
  a + "/svelte/components/modal/examples",
  a + "/svelte/components/modal/api",
  a + "/svelte/components/modal/playground",
  a + "/svelte/components/pagination/examples",
  a + "/svelte/components/pagination/api",
  a + "/svelte/components/pagination/playground",
  a + "/svelte/components/rating/examples",
  a + "/svelte/components/rating/api",
  a + "/svelte/components/rating/playground"
], d = "7eadc16c4fcd2684600d2414e41091e1bce4ddee", o = `cache-${d}`, c = [...l.map((s) => s.replace(/\/index\.html$/, "/")), ...b, ...i], r = (s) => {
  const e = [], t = [], p = /[.-]\w{8,}\.\w{2,4}$/;
  for (const n of s)
    (p.test(n) ? e : t).push(n);
  return { withHash: e, withoutHash: t };
};
self.addEventListener("install", (s) => {
  s.waitUntil(
    (async () => {
      const e = await caches.open(o), { withHash: t, withoutHash: p } = r(c), n = [];
      await Promise.all(
        t.map(async (u) => {
          const m = await caches.match(u);
          m != null && m.ok ? e.put(u, m) : n.push(u);
        })
      ), await e.addAll([...n, ...p]), await self.skipWaiting();
    })()
  );
});
self.addEventListener("activate", (s) => {
  s.waitUntil(
    (async () => {
      await self.clients.claim(), await Promise.all((await caches.keys()).filter((e) => e !== o).map((e) => caches.delete(e)));
    })()
  );
});
self.addEventListener("fetch", (s) => {
  const e = new URL(s.request.url);
  s.request.method === "GET" && c.includes(e.pathname) && s.respondWith(
    (async () => await (await caches.open(o)).match(e.pathname))()
  );
});
