const a = /* @__PURE__ */ location.pathname.split("/").slice(0, -1).join("/"), i = [
  a + "/_app/immutable/chunks/customHeaders.route.1f164f3d.js",
  a + "/_app/immutable/chunks/default.route.94ec572f.js",
  a + "/_app/immutable/chunks/playground.route.46c0da6a.js",
  a + "/_app/immutable/chunks/togglePanels.route.abd5e775.js",
  a + "/_app/immutable/chunks/dynamic.route.f021ca5a.js",
  a + "/_app/immutable/chunks/generic.route.bd019e4d.js",
  a + "/_app/immutable/chunks/icon.route.b7621b67.js",
  a + "/_app/immutable/chunks/playground.route.9849177e.js",
  a + "/_app/immutable/chunks/default.route.7eab3b38.js",
  a + "/_app/immutable/chunks/playground.route.8466cd94.js",
  a + "/_app/immutable/chunks/stack.route.faa82121.js",
  a + "/_app/immutable/chunks/custom.route.a4a29ccf.js",
  a + "/_app/immutable/chunks/default.route.f48d5a61.js",
  a + "/_app/immutable/chunks/playground.route.04efcbb9.js",
  a + "/_app/immutable/chunks/default.route.0dcdde20.js",
  a + "/_app/immutable/chunks/fullCustom.route.d455c7b3.js",
  a + "/_app/immutable/chunks/playground.route.dcf910f3.js",
  a + "/_app/immutable/chunks/simpleCustom.route.26619084.js",
  a + "/_app/immutable/chunks/customTemplate.route.9db4fc96.js",
  a + "/_app/immutable/chunks/default.route.55fc3d38.js",
  a + "/_app/immutable/chunks/form.route.40e90854.js",
  a + "/_app/immutable/chunks/playground.route.163e5f61.js",
  a + "/_app/immutable/chunks/readonly.route.cf980719.js",
  a + "/_app/immutable/chunks/body.02168975.js",
  a + "/_app/immutable/chunks/custom.3342281e.js",
  a + "/_app/immutable/chunks/custom.16b7efb9.js",
  a + "/_app/immutable/chunks/custom.02c85674.js",
  a + "/_app/immutable/chunks/readonly.e5e40f04.js",
  a + "/_app/immutable/entry/start.7140cbd8.js",
  a + "/_app/immutable/chunks/CustomHeaders.route.1b0dab19.js",
  a + "/_app/immutable/chunks/Default.route.14c8ff60.js",
  a + "/_app/immutable/chunks/Playground.route.8dd436c1.js",
  a + "/_app/immutable/chunks/TogglePanels.route.2a531565.js",
  a + "/_app/immutable/chunks/Dynamic.route.bb88327f.js",
  a + "/_app/immutable/chunks/Generic.route.04795f7a.js",
  a + "/_app/immutable/chunks/Icon.route.8c565e61.js",
  a + "/_app/immutable/chunks/Playground.route.13869e0f.js",
  a + "/_app/immutable/chunks/Default.route.ed075beb.js",
  a + "/_app/immutable/chunks/Playground.route.a1543103.js",
  a + "/_app/immutable/chunks/Stack.route.b3c246c3.js",
  a + "/_app/immutable/chunks/Custom.route.d9802bfa.js",
  a + "/_app/immutable/chunks/Default.route.43197433.js",
  a + "/_app/immutable/chunks/Playground.route.3677c70b.js",
  a + "/_app/immutable/chunks/Default.route.0225dc5b.js",
  a + "/_app/immutable/chunks/FullCustom.route.50efaaaa.js",
  a + "/_app/immutable/chunks/Playground.route.cc54ac06.js",
  a + "/_app/immutable/chunks/SimpleCustom.route.56b10f6f.js",
  a + "/_app/immutable/chunks/CustomTemplate.route.4a859403.js",
  a + "/_app/immutable/chunks/Default.route.67acd204.js",
  a + "/_app/immutable/chunks/Form.route.264b2bef.js",
  a + "/_app/immutable/chunks/Playground.route.5df093c9.js",
  a + "/_app/immutable/chunks/Readonly.route.50e1d6ab.js",
  a + "/_app/immutable/chunks/CustomHeaders.route.559bc62f.js",
  a + "/_app/immutable/chunks/Default.route.1256e20b.js",
  a + "/_app/immutable/chunks/Playground.route.775a1773.js",
  a + "/_app/immutable/chunks/TogglePanels.route.f8e4b7be.js",
  a + "/_app/immutable/chunks/Dynamic.route.a9d9e874.js",
  a + "/_app/immutable/chunks/Generic.route.8bab0d48.js",
  a + "/_app/immutable/chunks/Icon.route.07dd69d1.js",
  a + "/_app/immutable/chunks/Icon.2156b2f4.js",
  a + "/_app/immutable/chunks/Playground.route.2cdc4cab.js",
  a + "/_app/immutable/chunks/Default.route.1021abc6.js",
  a + "/_app/immutable/chunks/Playground.route.408a8117.js",
  a + "/_app/immutable/chunks/Stack.route.0d7a1533.js",
  a + "/_app/immutable/chunks/StackModal.e85f6954.js",
  a + "/_app/immutable/chunks/Custom.route.629bc057.js",
  a + "/_app/immutable/chunks/CustomPages.efa871a7.js",
  a + "/_app/immutable/chunks/Default.route.b3f56491.js",
  a + "/_app/immutable/chunks/Playground.route.f6c2d11b.js",
  a + "/_app/immutable/chunks/Coffee.4a37f4aa.js",
  a + "/_app/immutable/chunks/Default.route.e30b0943.js",
  a + "/_app/immutable/chunks/FullCustom.route.ca004f25.js",
  a + "/_app/immutable/chunks/Playground.route.82f93853.js",
  a + "/_app/immutable/chunks/SimpleCustom.route.aabbcc7b.js",
  a + "/_app/immutable/chunks/CustomTemplate.route.4720e965.js",
  a + "/_app/immutable/chunks/Default.route.dbc6041b.js",
  a + "/_app/immutable/chunks/Form.route.3beb4f72.js",
  a + "/_app/immutable/chunks/Playground.route.a1a7efc0.js",
  a + "/_app/immutable/chunks/Readonly.route.fa8fb3b8.js",
  a + "/_app/immutable/entry/app.38b6e44b.js",
  a + "/_app/immutable/assets/0.7d5b7f2b.css",
  a + "/_app/immutable/nodes/0.3ff8bb19.js",
  a + "/_app/immutable/nodes/1.e63f5a30.js",
  a + "/_app/immutable/nodes/10.2e33b3b5.js",
  a + "/_app/immutable/nodes/11.aa1ceb20.js",
  a + "/_app/immutable/nodes/12.047a3820.js",
  a + "/_app/immutable/nodes/13.74777fe1.js",
  a + "/_app/immutable/nodes/14.ef146b64.js",
  a + "/_app/immutable/nodes/15.69330408.js",
  a + "/_app/immutable/nodes/16.f909cccd.js",
  a + "/_app/immutable/nodes/17.768498b9.js",
  a + "/_app/immutable/nodes/18.d6e78b25.js",
  a + "/_app/immutable/nodes/19.74ca63a2.js",
  a + "/_app/immutable/assets/2.3358d9b6.css",
  a + "/_app/immutable/nodes/2.3b733384.js",
  a + "/_app/immutable/nodes/20.02fa6d0f.js",
  a + "/_app/immutable/nodes/21.b73fc22c.js",
  a + "/_app/immutable/nodes/22.cfb63bd6.js",
  a + "/_app/immutable/nodes/23.647eb6a5.js",
  a + "/_app/immutable/nodes/24.9ef16756.js",
  a + "/_app/immutable/nodes/25.1a545238.js",
  a + "/_app/immutable/nodes/26.222df190.js",
  a + "/_app/immutable/nodes/27.6a0b45fe.js",
  a + "/_app/immutable/nodes/28.160446b1.js",
  a + "/_app/immutable/nodes/29.1698a5dc.js",
  a + "/_app/immutable/nodes/3.3d1cc5a5.js",
  a + "/_app/immutable/nodes/30.9e9ed58d.js",
  a + "/_app/immutable/nodes/31.91f64a25.js",
  a + "/_app/immutable/nodes/32.dc42451a.js",
  a + "/_app/immutable/nodes/33.f67d447d.js",
  a + "/_app/immutable/nodes/34.c1baf1f5.js",
  a + "/_app/immutable/nodes/4.d99ee93a.js",
  a + "/_app/immutable/nodes/5.55889559.js",
  a + "/_app/immutable/nodes/6.e3f9c52d.js",
  a + "/_app/immutable/nodes/7.e612d0ef.js",
  a + "/_app/immutable/nodes/8.cefc232c.js",
  a + "/_app/immutable/assets/9.e8defed5.css",
  a + "/_app/immutable/nodes/9.f6171a4d.js",
  a + "/_app/immutable/assets/ApiDoc.88a4ab5e.css",
  a + "/_app/immutable/assets/Playground.4dc7c976.css",
  a + "/_app/immutable/assets/Sample.fd01a369.css",
  a + "/_app/immutable/assets/Section.b3133932.css",
  a + "/_app/immutable/assets/TOC.7c31d48f.css",
  a + "/_app/immutable/chunks/ApiDoc.aa22665e.js",
  a + "/_app/immutable/chunks/ComponentPage.3ba115d1.js",
  a + "/_app/immutable/chunks/Playground.e2a7f2fe.js",
  a + "/_app/immutable/chunks/Sample.8b95a82b.js",
  a + "/_app/immutable/chunks/Section.9252dab5.js",
  a + "/_app/immutable/chunks/Svg.de0de4b3.js",
  a + "/_app/immutable/chunks/TOC.464fb420.js",
  a + "/_app/immutable/chunks/api.1fade9b4.js",
  a + "/_app/immutable/chunks/api.381c68fb.js",
  a + "/_app/immutable/chunks/api.3c65a3b5.js",
  a + "/_app/immutable/chunks/api.8565129e.js",
  a + "/_app/immutable/chunks/api.cbab05d9.js",
  a + "/_app/immutable/chunks/app.e2ea7819.js",
  a + "/_app/immutable/chunks/collapse.166f4271.js",
  a + "/_app/immutable/chunks/cssTransitions.21643ea1.js",
  a + "/_app/immutable/chunks/each.870f7cce.js",
  a + "/_app/immutable/chunks/fade.e6e5d115.js",
  a + "/_app/immutable/chunks/index.3e38ccef.js",
  a + "/_app/immutable/chunks/navigation.0e13d369.js",
  a + "/_app/immutable/chunks/pagination.960ce093.js",
  a + "/_app/immutable/chunks/preload-helper.a4192956.js",
  a + "/_app/immutable/chunks/progressbar.8e4847bb.js",
  a + "/_app/immutable/chunks/rating.71539870.js",
  a + "/_app/immutable/chunks/scheduler.cb6605ed.js",
  a + "/_app/immutable/chunks/singletons.ec0d4c3d.js",
  a + "/_app/immutable/chunks/stores.2b7005b1.js",
  a + "/_app/immutable/chunks/stores.ce298bf5.js",
  a + "/_app/immutable/chunks/tooltip.86f6ef1d.js",
  a + "/angular/samples/3rdpartylicenses.txt",
  a + "/angular/samples/agnosui-logo.svg",
  a + "/angular/samples/assets/logo.svg",
  a + "/angular/samples/index.html",
  a + "/angular/samples/main.d061b24c547162c7.js",
  a + "/angular/samples/polyfills.bf6b4fcc1e9ebf5d.js",
  a + "/angular/samples/runtime.c73397b5506956dd.js",
  a + "/angular/samples/styles.8f172c3097baf266.css",
  a + "/react/samples/assets/agnosui-logo-ca3f4bd6.svg",
  a + "/react/samples/assets/index-5c0e5348.css",
  a + "/react/samples/assets/index-e212313b.js",
  a + "/react/samples/index.html",
  a + "/_app/immutable/assets/Code.d6edfd12.css",
  a + "/_app/immutable/chunks/Code.6a85321f.js",
  a + "/_app/immutable/chunks/angular.3603f7b0.js",
  a + "/_app/immutable/chunks/index.b0b8c4e5.js",
  a + "/_app/immutable/chunks/package.0ebfdbd5.js",
  a + "/_app/immutable/chunks/polyfills.ca93877f.js",
  a + "/_app/immutable/chunks/raw-loader.d.af52f768.js",
  a + "/_app/immutable/chunks/tsconfig.410825bf.js",
  a + "/_app/immutable/chunks/index.fb47ed10.js",
  a + "/_app/immutable/chunks/index.1063d445.js",
  a + "/_app/immutable/chunks/package.11639a52.js",
  a + "/_app/immutable/chunks/vite-env.d.7838e369.js",
  a + "/_app/immutable/chunks/tsconfig.6bbdde4a.js",
  a + "/_app/immutable/chunks/vite.config.9d6850ed.js",
  a + "/_app/immutable/chunks/index.637f3b0f.js",
  a + "/_app/immutable/chunks/package.5aee3c1f.js",
  a + "/_app/immutable/chunks/vite-env.d.2f957e98.js",
  a + "/_app/immutable/chunks/svelte.config.1307a686.js",
  a + "/_app/immutable/chunks/tsconfig.f25b7c9b.js",
  a + "/_app/immutable/chunks/vite.config.17a73b3a.js",
  a + "/svelte/samples/assets/agnosui-logo-ca3f4bd6.svg",
  a + "/svelte/samples/assets/index-23b98771.css",
  a + "/svelte/samples/assets/index-34aac2d1.js",
  a + "/svelte/samples/index.html",
  a + "/version.json"
], b = [
  a + "/agnosui-logo.svg"
], r = [
  a + "/",
  a + "/angular/getting-started/installation",
  a + "/react/getting-started/installation",
  a + "/svelte/getting-started/installation",
  a + "/angular/components/accordion",
  a + "/angular/components/alert",
  a + "/angular/components/modal",
  a + "/angular/components/pagination",
  a + "/angular/components/progressbar",
  a + "/angular/components/rating",
  a + "/react/components/accordion",
  a + "/react/components/alert",
  a + "/react/components/modal",
  a + "/react/components/pagination",
  a + "/react/components/progressbar",
  a + "/react/components/rating",
  a + "/svelte/components/accordion",
  a + "/svelte/components/alert",
  a + "/svelte/components/modal",
  a + "/svelte/components/pagination",
  a + "/svelte/components/progressbar",
  a + "/svelte/components/rating",
  a + "/angular/components/accordion/examples",
  a + "/angular/components/accordion/api",
  a + "/angular/components/accordion/playground",
  a + "/angular/components/alert/examples",
  a + "/angular/components/alert/api",
  a + "/angular/components/alert/playground",
  a + "/angular/components/modal/examples",
  a + "/angular/components/modal/api",
  a + "/angular/components/modal/playground",
  a + "/angular/components/pagination/examples",
  a + "/angular/components/pagination/api",
  a + "/angular/components/pagination/playground",
  a + "/angular/components/progressbar/examples",
  a + "/angular/components/progressbar/api",
  a + "/angular/components/progressbar/playground",
  a + "/angular/components/rating/examples",
  a + "/angular/components/rating/api",
  a + "/angular/components/rating/playground",
  a + "/react/components/accordion/examples",
  a + "/react/components/accordion/api",
  a + "/react/components/accordion/playground",
  a + "/react/components/alert/examples",
  a + "/react/components/alert/api",
  a + "/react/components/alert/playground",
  a + "/react/components/modal/examples",
  a + "/react/components/modal/api",
  a + "/react/components/modal/playground",
  a + "/react/components/pagination/examples",
  a + "/react/components/pagination/api",
  a + "/react/components/pagination/playground",
  a + "/react/components/progressbar/examples",
  a + "/react/components/progressbar/api",
  a + "/react/components/progressbar/playground",
  a + "/react/components/rating/examples",
  a + "/react/components/rating/api",
  a + "/react/components/rating/playground",
  a + "/svelte/components/accordion/examples",
  a + "/svelte/components/accordion/api",
  a + "/svelte/components/accordion/playground",
  a + "/svelte/components/alert/examples",
  a + "/svelte/components/alert/api",
  a + "/svelte/components/alert/playground",
  a + "/svelte/components/modal/examples",
  a + "/svelte/components/modal/api",
  a + "/svelte/components/modal/playground",
  a + "/svelte/components/pagination/examples",
  a + "/svelte/components/pagination/api",
  a + "/svelte/components/pagination/playground",
  a + "/svelte/components/progressbar/examples",
  a + "/svelte/components/progressbar/api",
  a + "/svelte/components/progressbar/playground",
  a + "/svelte/components/rating/examples",
  a + "/svelte/components/rating/api",
  a + "/svelte/components/rating/playground"
], d = "ac36f8cbea263c36333651f61e6ab94bb8e5cb9e", c = `cache-${self.registration.scope}-`, o = `${c}${d}`, l = [...i.map((s) => s.replace(/\/index\.html$/, "/")), ...r, ...b], _ = (s) => {
  const e = [], t = [], p = /[.-]\w{8,}\.\w{2,4}$/;
  for (const n of s)
    (p.test(n) ? e : t).push(n);
  return { withHash: e, withoutHash: t };
};
self.addEventListener("install", (s) => {
  s.waitUntil(
    (async () => {
      const e = await caches.open(o), { withHash: t, withoutHash: p } = _(l), n = [];
      await Promise.all(
        t.map(async (u) => {
          const m = await caches.match(u);
          m != null && m.ok ? e.put(u, m) : n.push(u);
        })
      ), await e.addAll([...n, ...p]), await self.skipWaiting();
    })()
  );
});
self.addEventListener("activate", (s) => {
  s.waitUntil(
    (async () => {
      await self.clients.claim(), await Promise.all((await caches.keys()).filter((e) => e.startsWith(c) && e !== o).map((e) => caches.delete(e)));
    })()
  );
});
self.addEventListener("fetch", (s) => {
  const e = new URL(s.request.url);
  s.request.method === "GET" && l.includes(e.pathname) && s.respondWith(
    (async () => {
      const t = await caches.open(o), p = await t.match(e.pathname);
      return p || (await t.add(e.pathname), await t.match(e.pathname));
    })()
  );
});
