name: ci
on:
  push:
    branches: [main, release/**]
jobs:
  build:
    needs: e2e-tests
    uses: './.github/workflows/build.yml'
    with:
      docPath: ${{ github.ref_name }}
      docPublish: true
  e2e-tests:
    uses: './.github/workflows/e2e-tests.yml'
