name: ci
on:
  push:
    branches: [main]
jobs:
  build:
    needs: e2e-tests
    uses: './.github/workflows/build.yml'
    with:
      docPath: main
      docPublish: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  e2e-tests:
    uses: './.github/workflows/e2e-tests.yml'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
