name: pr
on:
  pull_request:
    branches: [main, release/**]
jobs:
  build:
    uses: './.github/workflows/build.yml'
  validate-os:
    uses: './.github/workflows/validate-os.yml'
  e2e-tests:
    uses: './.github/workflows/e2e-tests.yml'
