name: pr
on:
  pull_request:
    branches: [main, release/**]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  build:
    uses: './.github/workflows/build.yml'
  validate-os:
    uses: './.github/workflows/validate-os.yml'
  e2e-tests:
    uses: './.github/workflows/e2e-tests.yml'
