name: release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version number (x.y.z)

jobs:
  build:
    uses: './.github/workflows/build.yml'
    with:
      version: ${{ inputs.version }}
      npmPublish: true
      docPublish: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
